export const SET_CURRENT_BOOK = "SET_CURRENT_BOOK";
export const CLEAR_SEARCH = "CLEAR_SEARCH";

export const FETCH_BOOKS_BEGIN   = 'FETCH_BOOKS_BEGIN';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';